version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: openpos-backend
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./backend/log:/app/log
      - ./ACPO:/app/ACPO
    ports:
      - "8000:8000"
    networks:
      - openpos

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: openpos-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:8000
    networks:
      - openpos

networks:
  openpos:
    driver: bridge